---
- name: Execute FIO Random IO
  delegate_to: "{{ fio_vm }}"
  run_once: true
  with_items:
      - "{{ groups['vm'] }}"
  loop_control:
      loop_var: fio_vm
  shell: 'fio --name=randomread --ioengine=libaio --iodepth="{{ iodepth }}" --rw=randread --end_fsync=1 --direct=1 --bs=4k --directory="{{ fio_test_directory }}" --filename_format=f.\$jobnum.\$filenum --filesize=16g --size=16g --time_based=1 --runtime=120 --numjobs="{{ fio_jobs }}" > "{{ fio_dir }}"/"{{ test }}" '
...
