---
- name: Install fio package
  shell: yum install fio -y
  register: any_error

- name: Create FIO Directory
  file:
    path="{{ fio_dir }}"
    state=directory

- name: Copying FIO Process Poll program
  template:
      src: pid_check.py.j2
      dest: /root/pid_check.py
...
