---
- name: Execute FIO Random Read
  run_once: true
  delegate_to: "{{ fio_host }}"
  shell: 'nohup fio --name=randomread --ioengine=libaio --iodepth="{{ iodepth }}" --rw=randread --direct=1 --bs=4k --directory={{ fio_test_directory }}/{{ fio_host }}/ --filename_format=f.\$jobnum.\$filenum --filesize="{{ fio_file_size }}" --size="{{ fio_job_size }}" --time_based=1 --runtime=120 --numjobs="{{ fio_jobs }}" > {{ fio_dir }}/{{ test }} &'
  with_items: "{{ groups['vm']}}"
  loop_control:
    loop_var: fio_host
...
