---
- name: Capture VDO STATUS -n <VDO_VOLUME_NAME>
  shell: 'vdo status -n "{{ vdo_volume_name }}" > "{{ vdo_logs }}"/vdo_status/"{{ test }}" &'
  ignore_errors: yes

- name: Capture VDOSTATS --hu
  shell: 'vdostats --hu  > "{{ vdo_logs }}"/vdo_stats/"{{ test }}" &'

- name: Capture VDOSTATS --verbose|grep bios|egrep -v 'par|co|ack|pr|use|f'
  shell: 'vdo status -n "{{ vdo_volume_name }}" > "{{ vdo_logs }}"/vdo_bio/"{{ test }}" &'
...
