---
- name: Execute FIO Sequential Write
  delegate_to: "{{ fio_vm }}"
  run_once: true
  with_items:
      - "{{ groups['vm'] }}"
  loop_control:
      loop_var: fio_vm
  shell: 'fio --name=initialwrite --ioengine=sync --rw=write --direct=0 --create_on_open=1 --fsync_on_close=1 --bs=128k --directory="{{ fio_test_directory }}" --filename_format=f.\$jobnum.\$filenum --filesize=16g --size=16g --numjobs="{{ fio_jobs }}" --dedupe_percentage="{{ dedupe_percentage }}" --refill_buffers=1 > "{{ fio_dir }}"/"{{ test }}"'
...
