---
- name: Execute FIO Sequential Write
  run_once: true
  delegate_to: "{{ fio_host }}"
  shell: 'fio --name=initialwrite --ioengine=sync --rw=write --direct=0 --create_on_open=1 --fsync_on_close=1 --bs=128k --directory="{{ fio_test_directory }}" --filename_format=f.\$jobnum.\$filenum --filesize=16g --size=16g --numjobs="{{ fio_jobs }}"  > "{{ fio_dir }}"/"{{ test }}"'
  with_items: "{{ groups['vm'] }}"
  loop_control:
    loop_var: fio_host
  when:
      - random_IO == "read"
...
