---
- name: Create VDO Logs Directory
  file:
    path="{{ vdo_logs }}"
    state=directory
  when: volume=='vdo'

- name: Create VDO Logs Sub-directories
  shell: 'mkdir -p "{{ vdo_logs }}"/"{{ item }}"'
  loop:
    - "vdo_stats"
    - "vdo_bio"
    - "vdo_status"
  when: volume=='vdo'

- name: Create Network Logs Directory
  file:
    path="{{ network_dir }}"
    state=directory
...
