---
- name: Execute FIO Sequential Read
  run_once: true
  delegate_to: "{{ fio_host }}"
  shell:  'nohup fio --name=sequentialread --ioengine=sync --rw=read  --bs=128k --directory={{ fio_test_directory }}/{{ fio_host }}/ --filename_format=f.\$jobnum.\$filenum --filesize="{{ fio_file_size }}" --size="{{ fio_job_size }}" --numjobs="{{ fio_jobs }}" > {{ fio_dir }}/{{ test }} &'
  with_items: "{{ groups['vm'] }}"
  loop_control:
    loop_var: fio_host
...
