---
- run_once: true
  delegate_to: "{{ groups['profiling_host'][0] }}"
  shell:  'gluster vol profile "{{ gluster_vol }}" stop'
  ignore_errors: yes

- run_once: true
  delegate_to: "{{ groups['profiling_host'][0] }}"
  shell:  'gluster vol profile "{{ gluster_vol }}" start'

...
