---
    - name: running test
      delegate_to: "{{ sysbenchVM }}"
      run_once: true
      shell: 'sysbench --db-driver=mysql --mysql-user=root --mysql-password="{{ mysql_root_password }}"  --mysql-db=sbtest --table_size="{{ sysbench_table_size }}" --tables="{{ sysbench_number_of_table }}"  --threads="{{ thread_count }}" /usr/share/sysbench/oltp_read_write.lua run > "{{ sysbench_dir }}"/"{{ test }}"'
...
