---

- name: Execute FIO Sequential Write on NORMAL volume
  run_once: true
  delegate_to: "{{ fio_host }}"
  shell: 'nohup fio --name=initialwrite --ioengine=sync --rw=write --direct=0 --create_on_open=1 --end_fsync=1 --bs=128k --filename_format=f.\$jobnum.\$filenum --directory={{ fio_test_directory }}/{{ fio_host }}/  --filesize={{ fio_file_size }} --size={{ fio_job_size }} --numjobs={{ fio_jobs }} > {{ fio_dir }}/{{ test }} &'
  loop: "{{ groups['vm'] }}"
  loop_control:
    loop_var: fio_host

...
