---

- name: Execute FIO Sequential Write on NORMAL volume
  run_once: true
  delegate_to: "{{ fio_host }}"
  shell: >
            'nohup fio --name=initialwrite --ioengine=sync --rw=write --direct=0 --create_on_open=1
            --end_fsync=1 --bs=128k --directory="{{ fio_test_directory }}"
            --filename_format=f.\$jobnum.\$filenum --filesize="{{ fio_file_size }}"
            --size="{{ fio_job_size }}" --numjobs="{{ fio_jobs }}" > "{{ fio_dir }}"/"{{ fio_host }}"/"{{ test }}" &'
  with_items: "{{ groups['vm'] }}"
  loop_control:
    loop_var: fio_host
  when: volume=="normal"

- name: Execute FIO Sequential Write on VDO volume
  run_once: true
  delegate_to: "{{ fio_host }}"
  shell: >
            'nohup fio --name=initialwrite --ioengine=sync --rw=write --direct=0 --create_on_open=1
            --end_fsync=1 --bs=128k --directory="{{ fio_test_directory }}"
            --filename_format=f.\$jobnum.\$filenum --filesize="{{ fio_file_size }}"
            --size="{{ fio_job_size }}" --numjobs="{{ fio_jobs }}"
            --dedupe_percentage="{{ dedupe_percentage }}" --refill_buffers=1 > "{{ fio_dir }}"/"{{ fio_host }}"/"{{ test }}" &'
  with_items: "{{ groups['vm'] }}"
  loop_control:
    loop_var: fio_host
  when: volume=="vdo"
...
