---
- name: Install fio package
  shell: yum install fio -y
  register: any_error

- name: Create FIO Directory
  file:
    path="{{ fio_dir }}"
    state=directory

- name: Role for Cloning Small file tool
  git:
      repo: "https://github.com/bengland2/smallfile.git"
      dest: /root/smallfile
      clone: yes
...
