---
- debug:
    var: test

- name: Start Gluster Profiling
  include_role:
      name: start_gluster_profile

- name: Record System Statistics
  include_role:
      name: record_stat

- name: execute fio sequential writes
  include_role:
      name: fio_sequential_write

- name: Hold for 10 seconds
  pause:
    seconds: 10

- name: FIO Process Polling initiated on FIO_VMs
  include_role:
        name: run_FIO_tracker

- name: include role for VDO
  hosts: rhhihosts
  include_role:
      name: capture_vdo_logs
  when: volume=='vdo'

- name: Capture Gluster Profiling
  include_role:
      name: capture_gluster_profile

- name: Stop Recording Statistics
  include_role:
      name: kill_stat

- name: Clear Caches
  include_role:
      name: clear_cache

- name: Change Env Vars for Sequential Read
  include_role:
      name: change_vars_for_sequential_read

- name: Hold for 3 seconds
  pause:
    seconds: 3

- name: Record Statistics
  include_role:
      name: record_stat

- name: Execute Fio Sequential Read
  include_role:
      name: fio_sequential_read

- name: Hold for 10 seconds
  pause:
    seconds: 10

- name: FIO Process Polling initiated on FIO_VMs
  include_role:
        name: run_FIO_tracker

- name: Capture Gluster Profiling
  include_role:
      name: capture_gluster_profile

- name: Stop Recording Statistics
  include_role:
      name: kill_stat

- name: include role for VDO
  include_role:
      name: capture_vdo_logs
  when: volume=='vdo'

- name: Change Vars for Random Reads
  include_role:
      name: change_vars_for_random_read

- name: Hold for 10 seconds
  pause:
     seconds: 3

- name: Record Statistics
  include_role:
      name: record_stat

- name: execute fio random read
  include_role:
      name: fio_random_read

- name: Hold for 10 seconds
  pause:
    seconds: 10

- name: FIO Process Polling initiated on FIO_VMs
  include_role:
        name: run_FIO_tracker

- name: Capture Gluster Profiling
  include_role:
      name: capture_gluster_profile

- name: include role for VDO
  hosts: rhhihosts
  include_role:
      name: capture_vdo_logs
  when: volume=='vdo'

- include_role:
      name: kill_stat

- include_role:
      name: clear_cache

- include_role:
      name: change_vars_for_random_write

- name: Hold for 3 seconds
  pause:
    seconds: 3

- include_role:
      name: record_stat

- include_role:
      name: fio_random_write

- name: Hold for 10 seconds
  pause:
     seconds: 10

- name: FIO Process Polling initiated on FIO_VMs
  include_role:
        name: run_FIO_tracker

- name: Capture Gluster Profiling
  include_role:
      name: capture_gluster_profile

- include_role:
      name: kill_stat

- include_role:
      name: capture_vdo_logs
  when: volume=='vdo'

- include_role:
      name: change_vars_for_sequential_write

- include_role:
      name: clear_fio_data

- include_role:
      name: clear_cache
...
