---
- name: SETTING UP OF WORKING ENVIRONMENT ON ALL
  hosts: all
  remote_user: root
  become: true
  roles:
    - common_env

- name: SETTING UP OF WORKING ENVIRONMENT ON Virtual Machine
  hosts: vm
  gather_facts: no
  remote_user: root
  become: true
  roles:
    - vm_env

- name: SETTING UP OF WORKING ENVIRONMENT ON HOSTS
  hosts: rhhihosts
  gather_facts: no
  remote_user: root
  become: true
  roles:
    - rhhihosts_env


- name: EXECUTING PERFORMANCE RUNS
  remote_user: root
  gather_facts: no
  hosts: child_hosts
  tasks:

   - name: Importing tasks
     include_tasks: fio_runs.yaml
     with_nested:
         - [16]
         - [0]
