---
- name: Install sysstat package
  become: true
  remote_user: root
  yum:
      state: present
      name:
          - sysstat

- file:
    path="{{ item }}"
    state=directory
  loop:
    - workdir_path
    - iostat_dir
    - vmstat_dir
    - mpstat_dir
    - network_dir
    - top_dir
    - pidstat_dir_1
    - pidstat_dir_2
...
