---
- name: Clear all data on the disk
  run_once: true
  delegate_to: "{{ fio_host }}"
  command: rm -rf '"{{ fio_test_directory }}"/*'
  with_items: "{{ groups['vm'] }}"
  loop_control:
    loop_var: fio_host
...
