---
- name: Execute FIO Random Write run on NORMAL volume
  run_once: true
  delegate_to: "{{ fio_host }}"
  shell: 'nohup fio --name=randomwrite --ioengine=libaio --iodepth="{{ iodepth }}" --rw=randwrite --end_fsync=1 --direct=1 --bs=4k --directory={{ fio_test_directory }}/{{ fio_host }}/ --filename_format=f.\$jobnum.\$filenum --filesize="{{ fio_file_size }}" -size={{ fio_job_size }} --time_based=1 --runtime=120 --numjobs="{{ fio_jobs }}" > {{ fio_dir }}/{{ test }} &'
  with_items: "{{ groups['vm'] }}"
  loop_control:
    loop_var: fio_host
  when: volume=='normal'

- name: Execute FIO Random Write run on VDO volume
  run_once: true
  delegate_to: "{{ fio_host }}"
  shell: 'nohup fio --name=randomwrite --ioengine=libaio --iodepth="{{ iodepth }}" --rw=randwrite --end_fsync=1 --direct=1 --bs=4k --directory={{ fio_test_directory }}/{{ fio_host }}/ --filename_format=f.\$jobnum.\$filenum --filesize="{{ fio_file_size }}" -size={{ fio_job_size }} --time_based=1 --runtime=120 --numjobs="{{ fio_jobs }}"   --dedupe_percentage="{{ dedupe_percentage }}" --refill_buffers=1 > {{ fio_dir }}/{{ test }} &'
  with_items: "{{ groups['vm'] }}"
  loop_control:
    loop_var: fio_host
  when: volume=='vdo'
...
